# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.24

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Produce verbose output by default.
VERBOSE = 1

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Users/iachaudray/homebrew/Cellar/cmake/3.24.2/bin/cmake

# The command to remove a file.
RM = /Users/iachaudray/homebrew/Cellar/cmake/3.24.2/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/iachaudray/CLionProjects/NBodySimulation

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/iachaudray/CLionProjects/NBodySimulation

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Users/iachaudray/homebrew/Cellar/cmake/3.24.2/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Users/iachaudray/homebrew/Cellar/cmake/3.24.2/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/iachaudray/CLionProjects/NBodySimulation/CMakeFiles /Users/iachaudray/CLionProjects/NBodySimulation//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/iachaudray/CLionProjects/NBodySimulation/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named NBodySimulation

# Build rule for target.
NBodySimulation: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NBodySimulation
.PHONY : NBodySimulation

# fast build rule for target.
NBodySimulation/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NBodySimulation.dir/build.make CMakeFiles/NBodySimulation.dir/build
.PHONY : NBodySimulation/fast

NBodySim/src/Application.o: NBodySim/src/Application.cpp.o
.PHONY : NBodySim/src/Application.o

# target to build an object file
NBodySim/src/Application.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NBodySimulation.dir/build.make CMakeFiles/NBodySimulation.dir/NBodySim/src/Application.cpp.o
.PHONY : NBodySim/src/Application.cpp.o

NBodySim/src/Application.i: NBodySim/src/Application.cpp.i
.PHONY : NBodySim/src/Application.i

# target to preprocess a source file
NBodySim/src/Application.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NBodySimulation.dir/build.make CMakeFiles/NBodySimulation.dir/NBodySim/src/Application.cpp.i
.PHONY : NBodySim/src/Application.cpp.i

NBodySim/src/Application.s: NBodySim/src/Application.cpp.s
.PHONY : NBodySim/src/Application.s

# target to generate assembly for a file
NBodySim/src/Application.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NBodySimulation.dir/build.make CMakeFiles/NBodySimulation.dir/NBodySim/src/Application.cpp.s
.PHONY : NBodySim/src/Application.cpp.s

NBodySim/src/EntryPoint.o: NBodySim/src/EntryPoint.cpp.o
.PHONY : NBodySim/src/EntryPoint.o

# target to build an object file
NBodySim/src/EntryPoint.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NBodySimulation.dir/build.make CMakeFiles/NBodySimulation.dir/NBodySim/src/EntryPoint.cpp.o
.PHONY : NBodySim/src/EntryPoint.cpp.o

NBodySim/src/EntryPoint.i: NBodySim/src/EntryPoint.cpp.i
.PHONY : NBodySim/src/EntryPoint.i

# target to preprocess a source file
NBodySim/src/EntryPoint.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NBodySimulation.dir/build.make CMakeFiles/NBodySimulation.dir/NBodySim/src/EntryPoint.cpp.i
.PHONY : NBodySim/src/EntryPoint.cpp.i

NBodySim/src/EntryPoint.s: NBodySim/src/EntryPoint.cpp.s
.PHONY : NBodySim/src/EntryPoint.s

# target to generate assembly for a file
NBodySim/src/EntryPoint.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NBodySimulation.dir/build.make CMakeFiles/NBodySimulation.dir/NBodySim/src/EntryPoint.cpp.s
.PHONY : NBodySim/src/EntryPoint.cpp.s

NBodySim/src/Window.o: NBodySim/src/Window.cpp.o
.PHONY : NBodySim/src/Window.o

# target to build an object file
NBodySim/src/Window.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NBodySimulation.dir/build.make CMakeFiles/NBodySimulation.dir/NBodySim/src/Window.cpp.o
.PHONY : NBodySim/src/Window.cpp.o

NBodySim/src/Window.i: NBodySim/src/Window.cpp.i
.PHONY : NBodySim/src/Window.i

# target to preprocess a source file
NBodySim/src/Window.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NBodySimulation.dir/build.make CMakeFiles/NBodySimulation.dir/NBodySim/src/Window.cpp.i
.PHONY : NBodySim/src/Window.cpp.i

NBodySim/src/Window.s: NBodySim/src/Window.cpp.s
.PHONY : NBodySim/src/Window.s

# target to generate assembly for a file
NBodySim/src/Window.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NBodySimulation.dir/build.make CMakeFiles/NBodySimulation.dir/NBodySim/src/Window.cpp.s
.PHONY : NBodySim/src/Window.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... NBodySimulation"
	@echo "... NBodySim/src/Application.o"
	@echo "... NBodySim/src/Application.i"
	@echo "... NBodySim/src/Application.s"
	@echo "... NBodySim/src/EntryPoint.o"
	@echo "... NBodySim/src/EntryPoint.i"
	@echo "... NBodySim/src/EntryPoint.s"
	@echo "... NBodySim/src/Window.o"
	@echo "... NBodySim/src/Window.i"
	@echo "... NBodySim/src/Window.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

